version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: pontigramid-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: pontigramid
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - pontigramid-network

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pontigramid-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/pontigramid?authSource=admin
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-production-secret-key-here
      - ADMIN_EMAIL=admin@pontigramid.com
      - ADMIN_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - pontigramid-network

volumes:
  mongodb_data:

networks:
  pontigramid-network:
    driver: bridge
